#ifndef  __VD_MACHINE_IO_H
#define  __VD_MACHINE_IO_H


#ifdef __cplusplus
extern "C"
{
#endif
    
#include "SysPeripheral/GPIO/GPIO_Man.h"


//输入IO编号
typedef enum
{
    //10个电机INDEX信号
    INPUT_IO_MOTRO_INDEX_INPUT1,
    INPUT_IO_MOTRO_INDEX_INPUT2,
    INPUT_IO_MOTRO_INDEX_INPUT3,
    INPUT_IO_MOTRO_INDEX_INPUT4,
    INPUT_IO_MOTRO_INDEX_INPUT5,
    INPUT_IO_MOTRO_INDEX_INPUT6,
    INPUT_IO_MOTRO_INDEX_INPUT7,
    INPUT_IO_MOTRO_INDEX_INPUT8,
    INPUT_IO_MOTRO_INDEX_INPUT9,
    INPUT_IO_MOTRO_INDEX_INPUT10,
    
    //7个通用INPUT
    INPUT_IO_INPUT11,
    INPUT_IO_INPUT12,
    INPUT_IO_INPUT13,
    INPUT_IO_INPUT14,
    INPUT_IO_INPUT15,
    INPUT_IO_INPUT16,
    INPUT_IO_INPUT17,
    

}INPUT_IO_TABLE;


//输出IO编号
typedef enum
{
    //LED指示灯 RUN1
    OUTPUT_IO_LED_RUN1 = 0,
    
    //EEPROM 
    OUTPUT_IO_I2C0_SCL,
    OUTPUT_IO_I2C0_SDA,
    
    //MOTOR DIR
    OUTPUT_IO_MOTOR_DIR,
    
    //4个OE_使能信号
    OUTPUT_IO_OE1_N,
    OUTPUT_IO_OE2_N,
    OUTPUT_IO_OE3_N,
    OUTPUT_IO_OE4_N,
    
    //10个电机行控制信号
    OUTPUT_IO_MOTRO_ROW_OUTPUT1,
    OUTPUT_IO_MOTRO_ROW_OUTPUT2,
    OUTPUT_IO_MOTRO_ROW_OUTPUT3,
    OUTPUT_IO_MOTRO_ROW_OUTPUT4,
    OUTPUT_IO_MOTRO_ROW_OUTPUT5,
    OUTPUT_IO_MOTRO_ROW_OUTPUT6,
    OUTPUT_IO_MOTRO_ROW_OUTPUT7,
    OUTPUT_IO_MOTRO_ROW_OUTPUT8,
    OUTPUT_IO_MOTRO_ROW_OUTPUT9,
    OUTPUT_IO_MOTRO_ROW_OUTPUT10,
    
    //10个电机列控制信号
    OUTPUT_IO_MOTRO_COL_OUTPUT11,
    OUTPUT_IO_MOTRO_COL_OUTPUT12,
    OUTPUT_IO_MOTRO_COL_OUTPUT13,
    OUTPUT_IO_MOTRO_COL_OUTPUT14,
    OUTPUT_IO_MOTRO_COL_OUTPUT15,
    OUTPUT_IO_MOTRO_COL_OUTPUT16,
    OUTPUT_IO_MOTRO_COL_OUTPUT17,
    OUTPUT_IO_MOTRO_COL_OUTPUT18,
    OUTPUT_IO_MOTRO_COL_OUTPUT19,
    OUTPUT_IO_MOTRO_COL_OUTPUT20,   
    
    //7个通用OUTPUT
    OUTPUT_IO_OUTPUT21,
    OUTPUT_IO_OUTPUT22, 
    OUTPUT_IO_OUTPUT23, 
    OUTPUT_IO_OUTPUT24, 
    OUTPUT_IO_OUTPUT25, 
    OUTPUT_IO_OUTPUT26, 
    OUTPUT_IO_OUTPUT27, 

}OUTPUT_IO_TABLE;


//格子柜控制IO资源表
extern GPIO_CTRL_TABLE g_VD1768_IOTable;
    
    

#ifdef __cplusplus
}
#endif


#endif /* __VD_MACHINE_IO_H */
