#ifndef  __HAL_IRQ_HANDLER_H
#define  __HAL_IRQ_HANDLER_H

#include "DataType/DataType.h"

#if defined(LPC17XX)

typedef enum
{
    //系统滴答
    IRQ_TRG_SYSTICK_UPDATE = 0,
    IRQ_TRG_SYSTICK_OS,
    
    //串口
    IRQ_TRG_UART0,
    IRQ_TRG_UART1,
    IRQ_TRG_UART2,
    IRQ_TRG_UART3,

    //DMA通道
    IRQ_TRG_DMA_CH1,
    IRQ_TRG_DMA_CH2,
    IRQ_TRG_DMA_CH3,
    IRQ_TRG_DMA_CH4,
    IRQ_TRG_DMA_CH5,
    IRQ_TRG_DMA_CH6,
    IRQ_TRG_DMA_CH7,
    IRQ_TRG_DMA_CH8,
    
    //GPIO中断
    IRQ_TRG_GPIOINT0_00,
    IRQ_TRG_GPIOINT0_01,
    IRQ_TRG_GPIOINT0_02,
    IRQ_TRG_GPIOINT0_03,
    IRQ_TRG_GPIOINT0_04,
    IRQ_TRG_GPIOINT0_05,
    IRQ_TRG_GPIOINT0_06,
    IRQ_TRG_GPIOINT0_07,
    IRQ_TRG_GPIOINT0_08,
    IRQ_TRG_GPIOINT0_09,
    IRQ_TRG_GPIOINT0_10,
    IRQ_TRG_GPIOINT0_11,
    IRQ_TRG_GPIOINT0_12,
    IRQ_TRG_GPIOINT0_13,
    IRQ_TRG_GPIOINT0_14,
    IRQ_TRG_GPIOINT0_15,
    IRQ_TRG_GPIOINT0_16,
    IRQ_TRG_GPIOINT0_17,
    IRQ_TRG_GPIOINT0_18,
    IRQ_TRG_GPIOINT0_19,
    IRQ_TRG_GPIOINT0_20,
    IRQ_TRG_GPIOINT0_21,
    IRQ_TRG_GPIOINT0_22,
    IRQ_TRG_GPIOINT0_23,
    IRQ_TRG_GPIOINT0_24,
    IRQ_TRG_GPIOINT0_25,
    IRQ_TRG_GPIOINT0_26,
    IRQ_TRG_GPIOINT0_27,
    IRQ_TRG_GPIOINT0_28,
    IRQ_TRG_GPIOINT0_29,
    IRQ_TRG_GPIOINT0_30,
    IRQ_TRG_GPIOINT0_31,

    IRQ_TRG_GPIOINT2_00,
    IRQ_TRG_GPIOINT2_01,
    IRQ_TRG_GPIOINT2_02,
    IRQ_TRG_GPIOINT2_03,
    IRQ_TRG_GPIOINT2_04,
    IRQ_TRG_GPIOINT2_05,
    IRQ_TRG_GPIOINT2_06,
    IRQ_TRG_GPIOINT2_07,
    IRQ_TRG_GPIOINT2_08,
    IRQ_TRG_GPIOINT2_09,
    IRQ_TRG_GPIOINT2_10,
    IRQ_TRG_GPIOINT2_11,
    IRQ_TRG_GPIOINT2_12,
    IRQ_TRG_GPIOINT2_13,
    IRQ_TRG_GPIOINT2_14,
    IRQ_TRG_GPIOINT2_15,
    IRQ_TRG_GPIOINT2_16,
    IRQ_TRG_GPIOINT2_17,
    IRQ_TRG_GPIOINT2_18,
    IRQ_TRG_GPIOINT2_19,
    IRQ_TRG_GPIOINT2_20,
    IRQ_TRG_GPIOINT2_21,
    IRQ_TRG_GPIOINT2_22,
    IRQ_TRG_GPIOINT2_23,
    IRQ_TRG_GPIOINT2_24,
    IRQ_TRG_GPIOINT2_25,
    IRQ_TRG_GPIOINT2_26,
    IRQ_TRG_GPIOINT2_27,
    IRQ_TRG_GPIOINT2_28,
    IRQ_TRG_GPIOINT2_29,
    IRQ_TRG_GPIOINT2_30,
    IRQ_TRG_GPIOINT2_31,
    
    //以太网
    IRQ_TRG_ENET,
    
    //定时器
    IRQ_TRG_TIME0,
    IRQ_TRG_TIME1,
    IRQ_TRG_TIME2,
    IRQ_TRG_TIME3,
    
}IRQ_TRIGGER_SOURCE;


#elif defined(STM32F10X)

typedef enum
{
    //系统滴答
    IRQ_TRG_SYSTICK_UPDATE = 0,
    IRQ_TRG_SYSTICK_OS,
    
    //外部中断
    IRQ_TRG_EXTI0,
    IRQ_TRG_EXTI1,
    IRQ_TRG_EXTI2,
    IRQ_TRG_EXTI3,
    IRQ_TRG_EXTI4,
    IRQ_TRG_EXTI5,
    IRQ_TRG_EXTI6,
    IRQ_TRG_EXTI7,
    IRQ_TRG_EXTI8,
    IRQ_TRG_EXTI9,
    IRQ_TRG_EXTI10,
    IRQ_TRG_EXTI11,
    IRQ_TRG_EXTI12,
    IRQ_TRG_EXTI13,
    IRQ_TRG_EXTI14,
    IRQ_TRG_EXTI15,
    
    //DMA中断
    IRQ_TRG_DMA1_Channel1,
    IRQ_TRG_DMA1_Channel2,
    IRQ_TRG_DMA1_Channel3,
    IRQ_TRG_DMA1_Channel4,
    IRQ_TRG_DMA1_Channel5,
    IRQ_TRG_DMA1_Channel6,
    IRQ_TRG_DMA1_Channel7,
    IRQ_TRG_DMA2_Channel1,
    IRQ_TRG_DMA2_Channel2,
    IRQ_TRG_DMA2_Channel3,
    IRQ_TRG_DMA2_Channel4,
    IRQ_TRG_DMA2_Channel5,
    
    IRQ_TRG_WWDG,
    IRQ_TRG_PVD,
    IRQ_TRG_TAMPER,
    IRQ_TRG_RTC,
    IRQ_TRG_FLASH,
    IRQ_TRG_RCC,
    IRQ_TRG_ADC1_2,
    IRQ_TRG_USB_HP_CAN1_TX,
    IRQ_TRG_USB_LP_CAN1_RX0,
    IRQ_TRG_CAN1_RX1,
    IRQ_TRG_CAN1_SCE,
    IRQ_TRG_TIM1_BRK,
    IRQ_TRG_TIM1_UP,
    IRQ_TRG_TIM1_TRG_COM,
    IRQ_TRG_TIM1_CC,
    IRQ_TRG_TIM2,
    IRQ_TRG_TIM3,
    IRQ_TRG_TIM4,
    IRQ_TRG_I2C1_EV,
    IRQ_TRG_I2C1_ER,
    IRQ_TRG_I2C2_EV,
    IRQ_TRG_I2C2_ER,
    IRQ_TRG_SPI1,
    IRQ_TRG_SPI2,
    IRQ_TRG_USART1,
    IRQ_TRG_USART2,
    IRQ_TRG_USART3,
    IRQ_TRG_RTCAlarm,
    IRQ_TRG_USBWakeUp,
    IRQ_TRG_TIM8_BRK,
    IRQ_TRG_TIM8_UP,
    IRQ_TRG_TIM8_TRG_COM,
    IRQ_TRG_TIM8_CC,
    IRQ_TRG_ADC3,
    IRQ_TRG_FSMC,
    IRQ_TRG_SDIO,
    IRQ_TRG_TIM5,
    IRQ_TRG_SPI3,
    IRQ_TRG_UART4,
    IRQ_TRG_UART5,
    IRQ_TRG_TIM6,
    IRQ_TRG_TIM7,
    
}IRQ_TRIGGER_SOURCE;

#endif

#ifdef __cplusplus
extern "C" {
#endif


/**
  * @brief  中断回调指针初始化
  * @param  None
  * @retval None
  */
void HAL_IRQ_Init(void);


/**
  * @brief  设置中断触发回调
  * @param  ptr 回调指针
  * @param  ulTrgSource 触发源
  * @retval None
  */
void HAL_IRQ_SetTrgCallback(void (*ptr)(void), uBit32 ulTrgSource);


/**
  * @brief  释放中断触发回调
  * @param  ulTrgSource 触发源
  * @retval None
  */
void HAL_IRQ_ReleaseTrgCallback(uBit32 ulTrgSource);


#ifdef __cplusplus
}
#endif

#endif /* __HAL_IRQ_HANDLER_H */
